# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNSShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!
    pod 'Google/SignIn'
    pod 'SDWebImage'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'Fabric'
    pod 'TwitterKit'
    pod 'Crashlytics'
    pod 'TwitterCore'

  # Pods for SNSShare

  target 'SNSShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
